prescottprue/cypress-firebase

src/buildFirestoreCommand.js

When an update command is sent to firestore the data for update is not included. Therefore the following error message is returned: 
`update() requires either a single javascript object or an alternating list of field/value pairs`
By adding the object data in the command the corresponding document gets updated successfully.

Appending firestore command to include the data for update

---

README.md

Improves explanation about how to create a Firebase service account and use it.

fix(docs): improve explanation of how to create a service account

---

cmds/createTestEnvFile.js
package-lock.json
package.json

* feat(createTestEnvFile): add  `FIREBASE_API_KEY ` to generated`cypress.env.json` (supports loading config from `firebase-ci` settings in `.firebaserc`)

v0.2.0-alpha.2

---

src/createTestEnvFile.js

…check if the user defines those claims. Use default isTesting claim if not defined
resolves #35

feat(auth): support passing developer claims when generating custom auth token

---

README.md

This PR adds an example for how to get and aliases the user id for the current logged in user.
Using Cypress alias allow us to get this value in a beforeEach call and use it later on, anywhere in the test.

Get current user ID example.

---

src/createTestEnvFile.js
src/utils.js

- utils now used the configured path instead of always
using hard-coded config file path location
- removed unnecessary exports and use of functions and paths to
reduce coupling

feat(core): support custom cypress config file path

---

README.md
index.d.ts
package.json
src/buildFirestoreCommand.ts
src/buildRtdbCommand.ts
src/createTestEnvFile.ts
src/utils.ts
test/unit/buildFirestoreCommand.spec.ts
test/unit/buildRtdbCommand.spec.ts

* fix(cy.callRtdb): only add `-d` flag when data is an object
* fix(cy.callFirestore): fixture path no longer stringified - #39
* feat(cy.callRtdb): fix writing a non object value with `set` - #60
* feat(tests): add tests for string value - #39
* feat(docs): add note to README about adding files to `.gitignore` - #23

v0.3.0-beta.4

---

README.md

Hi there, thanks for your project to let us have a chance to test firebase project with cypress.
You have done a great innovation job! I will continually follow your new footage. 
For this PR, I am just want to mention something about ```firebase-tools``` installation.
The case is that I failed to perform DELETE to Firestore using your ```cy.callFirestore```, and I found the error message in cypress is something like we haven’t ```firebase``` in ```node_modules/.bin```, we know that this folder contains some of the files as a link(symbol) of our packages installed in project(automatically) or globally(maybe we need do some extra job). 
Then after my observation, I found the ```firebase``` symbol is related to ```firebase-tools```, so each time we perform DELETE, we need this file in our …

fix(docs): note that firebase-tools should be installed locally instead of globally

---

examples/react-redux-firebase/yarn.lock
examples/typescript/yarn.lock
package.json
src/firebase-utils.ts

* fix(core): prevent `initializeApp` from being called multiple times when using emulators
* build(deps): bump acorn from 7.1.0 to 7.1.1 (#103) - @dependabot
* build(deps): bump acorn in /examples/react-redux-firebase (#105) - @dependabot

v1.0.0-beta.2

---

README.md

Minor tweaks to make startup instructions more accessible to Cypress newbies.

chore(docs): improve getting started instructions to handle case of never having run Cypress

---

README.md

`callFirestore("get", ...)` appears to return a single instance, not an array of instances.  `r[0]` is undefined.  `r.age` and `r.name` exist.  There does not appear to be a clear way to get `r.id` (though the caller knows the ID since they used it in the "get" call . . .)
If there is a way to get the metadata from a `callFirestore("get", ...)` or other approach, then it would be GREAT to add that to the example.

fix(docs): use correct checking logic in callFirestore example

---

README.md

In firestore, it is "delete".
I recommend getting a "remove" example added to the RTDB section.

fix(docs): use correct method name in callFirestore docs

---

README.md

Minor tweak to config to make it clearer that cypress-firebase plugin config is "just another plugin", as there might be other plugins/tasks to be registered.  For example, see https://github.com/prescottprue/cypress-firebase/issues/129 .

chore(docs): clarify usage with other plugins in setup

---

README.md

fix(docs): fix typo in firestore actionPath description

---

src/firebase-utils.ts

The message says "database url" but actually logged `projectId`

Fix the "Initialized app" message

---

README.md

Update README.md docs for Firebase Web SDK version 9.
When I update to Firebase Web SDK from v8 to v9, then the test was failed, because of breaking change of Firebase Web SDK v9 in commands.js.
I added 4 sentences for Firebase Web SDK v9, I wonder some of them are redundant.
But I consider Firebase Web SDK v9 will be a major coming soon, because the Firebase Web SDK v9 improved bundle size dramatically. So to prepare docs for Firebase Web SDK v9 is a good benefit for developers. We can reduce their struggling.

fix(docs): update code example for Firebase Web SDK version 9

---

README.md

I believe `overrideFirebaseConfig` should be passed to `cypressFirebasePlugin`

fix(docs): update config override example in README

---

README.md
index.d.ts
src/attachCustomCommands.ts

In our Cypress application we use multiple named Firebase applications. This PR is to add support for others with the same set of circumstances.
Tested with:
cypress 8.7.0
firebase 8.10.0
firebase-admin 10.0.0

feat(core): add support for passing app instance

---

README.md
index.d.ts
src/attachCustomCommands.ts
src/tasks.ts
test/unit/attachCustomCommands.spec.ts

Closes #194, closes #201 
Add support for tenants. This PR is a continuation of #201. The only change from #201 is that it's up to date with master and I've fixed the tests.
Tested it locally in my project, and it works as intended!
@prescottprue Let me know if you need something else from this PR for it to be merged

feat(commands): support for tenants in cy.login

---

package.json

Support firebase-admin@10 alongside 8 and 9. This PR allows npm users to avoid having to force install (using `npm install --legacy-peer-deps`) on newer versions of npm

fix(peer-deps): add v10 to supported versions for firebase-admin peer dependency 

---

package.json

* Adds support for firebase-admin v11 and higher by updating `peerDependencies` to `>8`

fix: support firebase-admin v11 and higher

---

README.md

* Remove `supportFile` setting from README example to avoid confusion (see #711)

chore(docs): remove support file path from example (#711)

---

src/tasks.ts
test/unit/tasks.spec.ts

Fixed a bug that firestore does not save as a date if the date exists in the map in the array.

fix(firestore): handle firestore date nested in object within array

---

examples/typescript/cypress/e2e/Firestore.cy.ts
package.json
src/attachCustomCommands.ts
src/firebase-utils.ts
src/tasks.ts
test/unit/tasks.spec.ts

Correctly handle parsing timestamps within `where` statements in `cy.callFirestore`
* closes #491

fix(firestore): correctly handle timestamp in where (#491)

---

src/tasks.ts

If a field has the literal value 0, this method will try to coerce it to a Timestamp, which is invalid. E.g:
`cy.callFirestore("set", "examples/example1", { val: 0 })`
This will lead to an error:
```
taskcallFirestore, Object{3}
(uncaught exception)CypressError: cy.task('callFirestore') failed with the following error:
> Value for argument "seconds" is not a valid integer.
```
This is because the expression `dataVal && dataVal.seconds` evaluates to 0 when dataVal is 0, as 0 is falsy:
```
// Run in any javascript console
const dataVal = 0;
typeof (dataVal && dataVal.seconds) === 'number';
-> true
```
I initially went with:
```
if (
typeof (dataVal?.seconds) === 'number' &&
typeof (dataVal?.nanoseconds) === 'number'
) {
return new firestoreStatics.Timestamp(dataVal.seconds, …
```

fix(callFirestore): prevent coercing 0 values 

---

src/firebase-utils.ts
src/tasks.ts
test/unit/tasks.spec.ts

Original PR here by @michaeldawson:  https://github.com/prescottprue/cypress-firebase/pull/1039
Created this PR to iron our lint issues and handling of `null` in an object. Updated tests to include confirming of `0` value

fix(callFirestore): prevent coercing 0 values  (#1039)

---

README.md

Node prefers ipv6 from version 17 https://github.com/nodejs/node/issues/40537

chore(docs): update firebase emulator recipe

---

.github/workflows/publish.yml

Fixes https://github.com/prescottprue/cypress-firebase/actions/runs/6018384481/job/16326480087#step:12:29

fix(ci): lock semantic to 18 to fix release

---

src/attachCustomCommands.ts

Using function overloading, define separate call types for the different actions of the `callFirestore()` method. Then use the built-in Firestore type declarations to tighten up the argument types for set/add/update etc.
Fixes #1172

feat(types): tighten up the types of callFirestore calls

---

README.md

The contents of `./serviceAccount.json` file are not picked up by default when running cypress-firebase locally, it possible having the contents of this file in your env as SERVICE_ACCOUNT used to be in the Google Service Account setup docs, but are not there anymore. 
It seems the `getServiceAccount` function doesn't throw when this is not present, leading to a `getaddrinfo ENOTFOUND metadata cypress-firebase` error that doesn't help any.
Hope this helps people in the future!

chore: add note about SERVICE_ACCOUNT env var for local

---

README.md
src/attachCustomCommands.ts
src/plugin.ts
src/tasks.ts
test/unit/attachCustomCommands.spec.ts
test/unit/plugin.spec.ts

I was in need of some Firebase Auth functions other than those provided by login, logout and getAuthUser, mainly functions like createAuthUser, importAuthUsers and deleteAuthUser(s).
Whilst adding those functions I thought, 'Why not add all of them, maybe I need them some day or someone else might?'
I had to rewrite plugin.ts to be more generalised.
I was unsure whether to give every auth function it's own task and custom command, or to to something like with callRtdb and callFirestore, where the first argument specified which function actually gets called.
Because of the plethora of different arguments needed in the Auth functions, I chose for the former. Also because this was quickest to implement. It does however 'pollute' the tasks and custom commands with lots of them.
If the latter …

feat: more auth functionality

---

src/firebase-utils.ts
test/unit/tasks.spec.ts

Fixes #1313
Adds a failing test first, where we have two documents that match the first two where conditions. If we are processing all three where conditions correctly, the query should uniquely identify a single document instead, to pass.
Verified the fix in a Cypress project of mine

fix(firestore): support unlimited number of where conditions
