- README.md
replace 'add' to be 'set' for fixing callFirestore example
> Add Full example for callFirestore

- cmds/createTestEnvFile.js
- package-lock.json
- package.json
- src/buildRtdbCommand.js
* feat(deps): update to firebase-tools-extra `v0.1.0-alpha.2` (improved fixture handling)
* fix(core): preserve existing `FIREBASE_PROJECT_ID` in `cypress.env.json`
> v0.2.0-alpha.3

- cmds/createTestEnvFile.js
- package-lock.json
- package.json
- src/buildRtdbCommand.js
* fix(createTestEnvFile): remove default of "local" when envArg is not provided
* feat(buildRtdbCommand): add case for RTDB `remove`
> v0.2.0-alpha.4

- package.json
- src/attachCustomCommands.ts
- src/buildFirestoreCommand.ts
- src/utils.ts
* fix(callFirestore): fix an issue when options aren't passed to `cy.callFirestore`
> v3.0.0-beta.2

- package.json
- src/attachCustomCommands.ts
- src/buildFirestoreCommand.ts
- src/buildRtdbCommand.ts
- src/node-utils.ts
- src/utils.ts
- test/.eslintrc.js
- test/setup.ts
- test/unit/attachCustomCommands.spec.ts
- test/unit/buildFirestoreCommand.spec.ts
- test/unit/buildRtdbCommand.spec.ts
- test/unit/index.spec.ts
- yarn.lock
* feat(core): add unit tests
* fix(callFirestore): fix `get` action passing invalid arguments
* fix(callRtdb): fix do not add project flag unless project is defined
* fix(createTestEnvFile): improve fallbacks for loading variables config/environment - #23
> v0.3.0-beta.3

- .github/workflows/publish.yml
- cmds/createTestEnvFile.js
- cmds/index.js
- package.json
- src/createTestEnvFile.ts
- yarn.lock
* feat(core): load `FIREBASE_PROJECT_ID` from service account instead of project config (helps with id misalignment)
* fix(ci): run `npm install` before publish (since dependencies such as `rimraf` are required)
* fix(deps): update `typescript` to `^3.7.4`
> v0.6.0-alpha.2

- .github/workflows/publish.yml
- README.md
- index.d.ts
- package.json
- src/attachCustomCommands.ts
- src/extendWithFirebaseConfig.ts
- src/firebase-utils.ts
- src/index.ts
- src/node-utils.ts
- src/pluginWithTasks.ts
- src/tasks.ts
- yarn.lock
* feat(core): add tasks support through `pluginWithTasks`
* feat(ci): add support for publishing to alpha tag
* fix(callFirestore): fix windows support for passing a fixture (through use of tasks) - #71
> v0.11.0-alpha.2

- .eslintignore
- examples/basic/.eslintrc.js
- examples/basic/cypress/integration/Firestore.spec.js
- examples/basic/cypress/integration/Rtdb.spec.js
- examples/basic/package.json
- examples/basic/yarn.lock
- index.d.ts
- package.json
- src/attachCustomCommands.ts
- src/buildFirestoreCommand.ts
- src/buildRtdbCommand.ts
- src/extendWithFirebaseConfig.ts
- src/firebase-utils.ts
- src/pluginWithTasks.ts
- src/tasks.ts
- yarn.lock
* chore(core): switch tasks to more clear api (options + data)
* chore(build): add lint-staged to pre-commit hook
* fix(callFirestore): improve querying through task to support where with limit
> v0.11.0-alpha.3

- package.json
- src/attachCustomCommands.ts
- src/firebase-utils.ts
* chore(tasks): only pass necessary information to task
* chore(utils): add logging to show that db has been initialized pointed to emulators
> v0.11.0-alpha.4

- .github/workflows/publish.yml
- index.d.ts
- package.json
- src/firebase-utils.ts
- src/node-utils.ts
* fix: pass application default credential when using emulators in attempt to fix "Error fetching access token"
* chore: add case for defaulting to SERVICE_ACCOUNT credential if it exists while using emulators (backup attempt to fix "Error fetching access token")
> v0.11.0-alpha.5

- .github/workflows/publish.yml
- .github/workflows/verify.yml
- index.d.ts
- package.json
- src/plugin.ts
- src/tasks.ts
- test/setup.ts
- test/unit/tasks-mocks.spec.ts
- test/unit/tasks.spec.ts
- tsconfig.json
- yarn.lock
* fix(callFirestore): handle a case where data function is undefined in firestore get
* feat(tests): add testing against emulators (#107)
> v1.0.0 beta.3

- README.md
> chore(docs): add link to cross-env in README - @gregfenton

- README.md
Some markup cleanup and minor hints to the instructions.
> fix(docs): format code sample in README - @gregfenton

- README.md
Fixed formatting of numbered list.
> fix(docs): use correct formatting in numbered listed in README - @gregfenton

- index.d.ts
- package.json
- src/tasks.ts
- test/unit/tasks.spec.ts
@prescottprue Feel free to pull it down and give it a try.. if you want me to make any changes let me know I'm not precious about anything 🙂
I also incremented the version in the package.json but happy to take that out if you have a different process for doing that.
Fixes  #132 - (callFirestore with serverTimestamp has unexpected results)
> feat(core): support serverTimestamp in firestore set

- package-lock.json
- package.json
- src/tasks.ts
- test/unit/extendWithFirebaseConfig.spec.ts
- test/unit/tasks.spec.ts
- yarn.lock
I tried to add a GeoPoint object from `callFirestore`.
But it was the Object that was saved.
Therefore, I modified it to convert to GeoPoint with the same logic as Timestamp.
> feat(callFirestore): support GeoPoint data type

- README.md
- index.d.ts
- src/attachCustomCommands.ts
- test/unit/attachCustomCommands.spec.ts
- yarn.lock
> feat(core): add support for passing app instance (#499) - @zymotik

- .github/workflows/publish.yml
- .github/workflows/verify.yml
* Remove matrix from concurrency setting name
> fix(ci): correctly set concurrency on verify workflow

- .github/workflows/publish.yml
> chore(ci): report coverage even when skipping publish

- .github/workflows/publish.yml
- .github/workflows/verify.yml
- .husky/commit-msg
- .prettierrc.js
- README.md
- commitlint.config.js
- package.json
- yarn.lock
* chore: only upload coverage for node 14
* chore: add prettier config
> chore(ci): switch publish to semantic-release

- README.md
> chore(docs): fix firebase link on README

- README.md
* Adds instruction about getting service account
* Adds api doc for plugin explaining overrides for firebase-admin
* closes #700 
* closes #715
> fix(docs): more detail on firebase-admin init (#700, #715)

- .github/workflows/publish.yml
> chore(ci): remove whoami

- .github/workflows/publish.yml
- package.json
- yarn.lock
> chore(ci): simplify publish workflow

- renovate.json
> chore: lock chai to v4 major

- package.json
> chore: update size check to 9kb
